project_id = "pnj-ebrochure"

[functions.pnj-product-import]
verify_jwt = false

[functions.seed-admin-users]
verify_jwt = false

[functions.media-library]
verify_jwt = false

[functions.sync-hotspot-prices]
verify_jwt = false
